#!/usr/bin/env python3
"""Prepare small native fixtures from the independently generated gzip reference."""
import hashlib
import json
from pathlib import Path

product = Path(__file__).resolve().parents[2]
reference = product / 'Tests/OpenWeightsCoreTests/Fixtures/gzip-reference.json'
fixtures = json.loads(reference.read_text())['fixtures']
lines = ['// Generated by Tests/WebGzipReference/generate_device.py. Do not edit.',
         'import Foundation', '', 'enum GzipPageReference {',
         '    static let sourceSHA256 = "' + hashlib.sha256(reference.read_bytes()).hexdigest() + '"']
for name, field in [('unicode', 'unicode'), ('bomb', 'expansion')]:
    fixture = fixtures[name]
    encoded = bytes.fromhex(fixture['gzipHex'])
    assert len(encoded) == fixture['encodedBytes']
    assert hashlib.sha256(encoded).hexdigest() == fixture['encodedSHA256']
    lines.append('    static let ' + field + 'Hex = "' + fixture['gzipHex'] + '"')
    lines.append('    static let ' + field + 'SHA256 = "' + fixture['encodedSHA256'] + '"')
lines += ['    static let unicodeText = "旅行 🌿 Cedar 730"',
          '    static let expansionDecodedBytes = 8_388_608', '}', '']
assert fixtures['unicode']['expectedText'] == '旅行 🌿 Cedar 730'
assert fixtures['bomb']['decodedBytes'] == 8_388_608
output = product / 'DeviceTests/GzipPageReference.swift'
output.write_text('\n'.join(lines))
print(output)
